// Types

// For APP
export const APP = {
    TOGGLE_LOADING: "TOGGLE_LOADING"
};

// For CHARACTERS
export const CHARACTERS = {
    FETCH_CHARACTERS: "FETCH_CHARACTERS",
    FETCH_SINGLE_CHARACTER: "FETCH_SINGLE_CHARACTER",
};

// For COMICS
export const COMICS = {
    FETCH_COMICS: "FETCH_COMICS",
    FETCH_SINGLE_COMICS: "FETCH_SINGLE_COMICS",
};